### 파이프라인

#### 팔머펭귄

>>X값분류
* iTER1. 
    - SCV같은 선형 분류 모델 하나 선정
    - 그리드 서치
    - 파이프라인 구현 

In [2]:
import numpy as np
import pandas as pd


In [3]:
df = pd.read_csv("data/penguins_size.csv")
df.sample(15)
##판다스에서 전체데이터 들어와서 헤더를 봐라 정리가 잘 되어있는지
##인포를 본다음 na가 적다면 그냥 지우는게 빠름 na값에 대한 태도를 정해야함 
##데이터는 연속성을 띈다. 관측데이터는 연속성이 안나타난다. 문자열은 다르게 할 방법은 없다.


species     island  culmen_length_mm  culmen_depth_mm  \
203  Chinstrap      Dream              51.4             19.0   
16      Adelie  Torgersen              38.7             19.0   
25      Adelie     Biscoe              35.3             18.9   
232     Gentoo     Biscoe              45.5             13.7   
293     Gentoo     Biscoe              46.5             14.8   
133     Adelie      Dream              37.5             18.5   
204  Chinstrap      Dream              45.7             17.3   
151     Adelie      Dream              41.5             18.5   
271     Gentoo     Biscoe              48.5             14.1   
273     Gentoo     Biscoe              50.1             15.0   
110     Adelie     Biscoe              38.1             16.5   
19      Adelie  Torgersen              46.0             21.5   
94      Adelie      Dream              36.2             17.3   
143     Adelie      Dream              40.7             17.0   
298     Gentoo     Biscoe              45.2             13.8   

     flipper_length_mm  body_mass_g     sex  
203              201.0       3950.0    MALE  
16               195.0       3450.0  FEMALE  
25               187.0       3800.0  FEMALE  
232              214.0       4650.0  FEMALE  
293              217.0       5200.0  FEMALE  
133              199.0       4475.0    MALE  
204              193.0       3600.0  FEMALE  
151              201.0       4000.0    MALE  
271              220.0       5300.0    MALE  
273              225.0       5000.0    MALE  
110              198.0       3825.0  FEMALE  
19               194.0       4200.0    MALE  
94               187.0       3300.0  FEMALE  
143              190.0       3725.0    MALE  
298              215.0       4750.0  FEMALE

In [4]:
df.isnull().sum()
##na값 확인

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [5]:
penguins= df.dropna()
##na값 드랍

In [6]:
penguins

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen              39.1             18.7              181.0   
1    Adelie  Torgersen              39.5             17.4              186.0   
2    Adelie  Torgersen              40.3             18.0              195.0   
4    Adelie  Torgersen              36.7             19.3              193.0   
5    Adelie  Torgersen              39.3             20.6              190.0   
..      ...        ...               ...              ...                ...   
338  Gentoo     Biscoe              47.2             13.7              214.0   
340  Gentoo     Biscoe              46.8             14.3              215.0   
341  Gentoo     Biscoe              50.4             15.7              222.0   
342  Gentoo     Biscoe              45.2             14.8              212.0   
343  Gentoo     Biscoe              49.9             16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
4         3450.0  FEMALE  
5         3650.0    MALE  
..           ...     ...  
338       4925.0  FEMALE  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[334 rows x 7 columns]

In [7]:
penguins.reset_index(drop =True, inplace=True )
##드랍하고 인덱스 리셋

In [8]:
penguins[penguins.sex== '.']
##성별 .인거 찾기

species  island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
327  Gentoo  Biscoe              44.5             15.7              217.0   

     body_mass_g sex  
327       4875.0   .

In [9]:
penguins.drop([327], inplace=True)
## 드랍.

C:\Users\user\AppData\Local\Temp\ipykernel_1880\4132608713.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  penguins.drop([327], inplace=True)


In [10]:
penguins['sex'].unique()

array(['MALE', 'FEMALE'], dtype=object)

In [11]:
penguins['species'] = penguins['species'].astype('category')
penguins['species_cod'] = penguins['species'].cat.codes

C:\Users\user\AppData\Local\Temp\ipykernel_1880\3177699378.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  penguins['species'] = penguins['species'].astype('category')
C:\Users\user\AppData\Local\Temp\ipykernel_1880\3177699378.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  penguins['species_cod'] = penguins['species'].cat.codes


In [12]:
penguins['species_cod']

0      0
1      0
2      0
3      0
4      0
      ..
329    2
330    2
331    2
332    2
333    2
Name: species_cod, Length: 333, dtype: int8

In [13]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
Index: 333 entries, 0 to 333
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   species            333 non-null    category
 1   island             333 non-null    object  
 2   culmen_length_mm   333 non-null    float64 
 3   culmen_depth_mm    333 non-null    float64 
 4   flipper_length_mm  333 non-null    float64 
 5   body_mass_g        333 non-null    float64 
 6   sex                333 non-null    object  
 7   species_cod        333 non-null    int8    
dtypes: category(1), float64(4), int8(1), object(2)
memory usage: 19.0+ KB


In [14]:
penguins_feats = ['island','culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g','sex']
penguins_labs=['species_cod']
X, y = penguins[penguins_feats].values,penguins[penguins_labs].values

## 사이킷런은 판다스의 인풋값이 넣어주면 자기가 알아서 리스트로 변경. 망할 파이프라인을 쓸려면 제어 권한인 우리한테와서 수동작업으로 x,y를 해서 컬럼값을 빼야한다.
## 인덱스 순서에 맞게 나열해서 리스트에 넣어야함.
## labs 답안지
##여기까지 전처리하고 사이킷런으로 넘어간다.

In [15]:
X,y

(array([['Torgersen', 39.1, 18.7, 181.0, 3750.0, 'MALE'],
        ['Torgersen', 39.5, 17.4, 186.0, 3800.0, 'FEMALE'],
        ['Torgersen', 40.3, 18.0, 195.0, 3250.0, 'FEMALE'],
        ...,
        ['Biscoe', 50.4, 15.7, 222.0, 5750.0, 'MALE'],
        ['Biscoe', 45.2, 14.8, 212.0, 5200.0, 'FEMALE'],
        ['Biscoe', 49.9, 16.1, 213.0, 5400.0, 'MALE']], dtype=object),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
  

#### SVC를 사용한 학습 및 평가

In [16]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.svm import SVC

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix


In [17]:
n_feats=[1,2,3,4]
n_tras = Pipeline(steps=[('scaler',StandardScaler())])
c_feats = [0,5]
c_tras = Pipeline(steps=[('OneHot',OneHotEncoder(handle_unknown='ignore'))])
#정의부

In [18]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num',n_tras,n_feats),
        ('cat', c_tras, c_feats)
    ]
)
#실행

In [19]:
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 [1, 2, 3, 4]),
                                ('cat',
                                 Pipeline(steps=[('OneHot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 [0, 5])])

In [20]:
Pipeline =Pipeline(steps=[('preprocessor',preprocessor),
                          ('svc',SVC(probability=True))
                          ])
#위의 파이프라인을 파이프라인에 넣는다.재귀
#문제를 풀 수 없을때 문제를 작게 만들어서 풀고 크기를 키워라.
#svc생성자 선언 svc 핏한다.
#분류문제 비지도 에 한해서 정규화 시킨다. svc,fit,prediction

In [21]:
SVC_scores = []
SVC_fimp = []
SVC_predictions = 0
FOLDS = 5
##사전에 필요한 값들

In [22]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [23]:
for fold, (train_idx, valid_idx) in enumerate(skf.split(penguins[penguins_feats].values,
                                                        penguins[penguins_labs].values)):
    print(f"FOld = {fold}")
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    X_val_train, X_val, y_val_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

    multi_model = Pipeline.fit(X_val_train,y_val_train)
    ##v파이프라인에 훈련값 피팅
    preds_valid = multi_model.predict(X_val)
    acc= accuracy_score(y_val,preds_valid)
    SVC_scores.append(acc)
    test_preds = multi_model.predict(X_test)
##split안에는 인덱스가 있는 애들이들어가야한다.
## 순회자 방법을 쓴다 (for each) 객체를 돌리는 것.
##enumerate는 (i,$)라고 나옴. fold는 index가 있는 정수값이 나와야함. 인덱스 순차대로 가다 숫자가 비면 순회가 안됨. 

FOld = 0
FOld = 1
FOld = 2
FOld = 3
FOld = 4


c:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1300: DataConversio

In [24]:
np.mean(SVC_scores)


0.9850746268656716

In [25]:
confusion_matrix(y_val,preds_valid)
#0,1,2,

array([[32,  0,  0],
       [ 1, 13,  0],
       [ 0,  0, 21]], dtype=int64)

In [26]:
preds_valid

array([2, 2, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2,
       2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1,
       0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2, 1, 0, 1, 2, 2, 2, 0,
       2], dtype=int8)

In [28]:
import xgboost as xgb
from sklearn.model_selection import(
    train_test_split
    gridsearchcv,
    cross_val_score
)
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import(
    RandomForestClassifier,
    ExtraTreesClassifier,
    AdaBoostClassifier
)
from sklearn.svm import SVC
from sklearn.cluster import Kmeans
from sklearn.metrics import(
    accuracy_score,
    confusion_matrix,
    classification_report
)

SyntaxError: invalid syntax (1719793132.py, line 4)

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    iris['data']
    iris['target']
    test_size=0.2
    random_state=42
)